services:
  nextjs:
    build:
      context: .  # 使用当前目录作为构建上下文
      dockerfile: Dockerfile  # 指定 Dockerfile 路径
    image: nextjs:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # 将宿主机的 80 端口映射到 Nginx 容器的 80 端口
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载 Nginx 配置文件
      - /usr/local/nginx/conf/cert:/etc/nginx/cert
    depends_on:
      - nextjs
    restart: always