import { JSX, SVGProps } from "react";
import {
  ReactIcon,
  SvelteIcon,
  VueIcon,
  RubyIcon,
  GitIcon,
  FlutterIcon,
  D3Icon,
  MatrixIcon,
  HexoIcon,
  NextIcon,
  NginxIcon,
  DockerIcon,
  SwiftIcon,
  CocoapodsIcon,
  AliCloudIcon,
  AsepriteIcon,
  LeafletIcon,
  GodotIcon,
  SteamIcon,
  TravelIcon,
  OthersIcon,
  GameIcon,
  OverseasIcon,
  DevelopIcon,
  AIIcon,
  BookIcon,
} from "@/components/icons";

export const tagConfigMap: Record<
  string,
  (svgProps: SVGProps<SVGSVGElement>) => JSX.Element
> = {
  react: ReactIcon,
  vue: VueIcon,
  svelte: SvelteIcon,
  ruby: RubyIcon,
  git: GitIcon,
  flutter: FlutterIcon,
  d3: D3Icon,
  math: MatrixIcon,
  hexo: HexoIcon,
  nextjs: NextIcon,
  nginx: NginxIcon,
  docker: DockerIcon,
  swift: SwiftIcon,
  cocoapods: CocoapodsIcon,
  阿里云: AliCloudIcon,
  像素: AsepriteIcon,
  leaflet: LeafletIcon,
  godot: GodotIcon,
  steam: SteamIcon,
  travel: TravelIcon,
  others: OthersIcon,
  game: GameIcon,
  overseas: OverseasIcon,
  develop: DevelopIcon,
  ai: AIIcon,
  book: BookIcon,
};
